spring.datasource.username = root
spring.datasource.password = 212420
spring.datasource.url = jdbc:mysql://localhost:3306/db_gamesapi?useTimezone=true&serverTimezone=UTC
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show_sql = true